admins/urls.py
from django.urls import path
from . import views
from admins.views import index, dashboard

app_name = 'admins'  # This registers the 'base' namespace

urlpatterns=[

   path('user/login/',views.index,name='user_login'),
   path('user/student/add', views.studentadd, name='studentadd'),
   path('user/student/edit/<int:id>/', views.studentedit, name='studentedit'),
   path('user/student/delete/<int:id>/', views.studentdelete, name='studentdelete'),

]

base/urls.py
from django.urls import path
from . import views
app_name = 'base'  # This registers the 'base' namespace

urlpatterns=[
   path('',views.index),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from admins.views import index, dashboard

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
    path('',include('admins.urls')),
    path('user/dashboard/', dashboard, name='dashboard'),

   
]

admins/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        return self.name

class Teacher(models.Model):
    name = models.CharField(max_length=100)
    phone = models.IntegerField(max_length=10)
    address = models.CharField(max_length=100)
    email = models.EmailField()
    image = models.CharField(max_length=100)

    def __str__(self):
        return self.name

base/models.py
from django.db import models

# Create your models here.

admins/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)

admins/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseBadRequest
from django.db.models import Q
from django.contrib import messages
from .forms import LoginForm
from .models import Student

from .models import Teacher
# Create your views here.
def index(request):
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')
		if username == 'admin@gmail.com' and password == 'Admin123':
			return redirect('dashboard')
		else:
			return HttpResponseBadRequest ("Invalid username or password. Please try again.")
	else:
		form = LoginForm()
	return render(request,'admins/index.html')


def dashboard(request):
	if 'q' in request.GET:
		q = request.GET['q']
		# all_student = Student.objects.filter(name__icontains=q)
		multiple_q = Q(Q(name__icontains=q) | Q(address__icontains=q) | Q(email__icontains=q))
		all_student = Student.objects.filter(multiple_q)
	else:
		all_student = Student.objects.all()

	return render(request, 'admins/dashboard.html', {'all': all_student})

def studentadd(request):
	if request.method == 'POST':
		name = request.POST.get('name')
		email = request.POST.get('email')
		address = request.POST.get('address')
		Student.objects.create(name=name,email=email,address=address)
		# Add a success message
		messages.success(request, 'Student Added successfully!')
		# Redirect to the student list page after successful update
		return redirect('dashboard')  # Replace 'student_list' with the name of your list view
	return render(request,'admins/student_add.html')


def studentedit(request, id):
	student = get_object_or_404(Student, id=id)
	if request.method == 'POST':
		# Update the student's fields
		student.name = request.POST.get('name')
		student.email = request.POST.get('email')
		student.address = request.POST.get('address')
		student.save()
		# Add a success message
		messages.success(request, 'Student updated successfully!')
		# Redirect to the student list page after successful update
		return redirect('dashboard')  # Replace 'student_list' with the name of your list view
	return render(request,'admins/student_edit.html', {'student':student})

def studentdelete(request, id):
	student = get_object_or_404(Student, id=id)
	student.delete()
	messages.success(request, 'Student deleted successfully !')
	return redirect('dashboard')

base/views.py
from django.shortcuts import render


# Create your views here.

def index(request):
	# messages.success(request, 'Incorrect Username or Password')
	return render(request,'base/index.html')

admins/templates/admins/dashboard.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Chisapani School Admin| Dashboard</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'admin/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bootstrap 4 -->
  <link rel="stylesheet" href="{% static 'admin/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'admin/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{% static 'admin/plugins/jqvmap/jqvmap.min.css'%}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'admin/dist/css/adminlte.min.css' %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'admin/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{% static 'admin/plugins/daterangepicker/daterangepicker.css' %}">
  <!-- summernote -->
  <link rel="stylesheet" href="{% static 'admin/plugins/summernote/summernote-bs4.min.css' %}">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      <li class="nav-item">
        <a class="nav-link" data-widget="navbar-search" href="#" role="button">
          <i class="fas fa-search"></i>
        </a>
        <div class="navbar-search-block">
          <form class="form-inline" method="GET" action="" id="stu_search">
            <div class="input-group input-group-sm">
              <input class="form-control form-control-navbar" type="search" name="q"  placeholder="Search by name,address,email" aria-label="Search">
              <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                  <i class="fas fa-search"></i>
                </button>
                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->

            <li class="nav-item">
            <a href="#" class="nav-link active">
              <i class="fas fa-users"></i>
              <p>
                Students
                <i class="bi bi-people-fill"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'admins:studentadd' %}" class="nav-link active">
                  <i class="fas fa-user-plus"></i>
                  <p>Add Student</p>
                </a>
              </li>

            </ul>
          </li>

        </ul>

      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Students List</h1>
            <!--          success message-->

          <div class="card-header">
              {% if messages %}
            <ul class="messages" style="color:green;list-style-type:none;font-size:20px;text-align:center;">
            {% for message in messages %}
              <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
            </ul>
             {% endif %}
          </div>

<!--          success message ends-->

          </div><!-- /.col -->


        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <!-- Small boxes (Stat box) -->

        <!-- Main row -->
        <div class="row">
          <!-- Left col -->
          <section class="col-lg-12 connectedSortable">

            <div class="card-body" id="search_result">
                <table class="table table-bordered">
                  <thead>
                    <tr>
                      <th style="width: 10px">S.N.</th>
                      <th>Name</th>
                      <th>Address</th>
                      <th>Email</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for item in all %}
                    <tr>
                      <td>{{ forloop.counter }}</td>
                      <td>{{item.name}}</td>
                      <td>{{item.address}}</td>
                      <td>{{item.email}}</td>
                      <td><a href="{% url 'admins:studentedit' item.id %}" title="edit"><i class="fas fa-edit"></i></a>&nbsp;|<a href="{% url 'admins:studentdelete' item.id %}" title="edit" onclick="return confirmDelete();">&nbsp;<i class="fas fa-trash"></i></td>
                      </a>
                    </tr>
                  {% empty %}
        <tr>
            <td colspan="5" style="text-align: center;">No Result found.</td>
        </tr>


                    {% endfor %}
                  </tbody>
                </table>
              </div>

          </section>
          <!-- /.Left col -->

        </div>
        <!-- /.row (main row) -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <strong>Copyright &copy; 2081 OJT batch <a href="#">Chisapani Model Secondary School</a>.</strong>
    All rights reserved.
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static 'admin/plugins/jquery/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'admin/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>

<!-- Bootstrap 4 -->
<script src="{% static 'admin/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- ChartJS -->
<script src="{% static 'admin/plugins/chart.js/Chart.min.js' %}"></script>
<!-- Sparkline -->
<script src="{% static 'admin/plugins/sparklines/sparkline.js' %}"></script>
<!-- JQVMap -->
<script src="{% static 'admin/plugins/jqvmap/jquery.vmap.min.js' %}"></script>
<script src="{% static 'admin/plugins/jqvmap/maps/jquery.vmap.usa.js' %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static 'admin/plugins/jquery-knob/jquery.knob.min.js' %}"></script>
<!-- daterangepicker -->
<script src="{% static 'admin/plugins/moment/moment.min.js' %}"></script>
<script src="{% static 'admin/plugins/daterangepicker/daterangepicker.js' %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static 'admin/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<!-- Summernote -->
<script src="{% static 'admin/plugins/summernote/summernote-bs4.min.js' %}"></script>
<!-- overlayScrollbars -->
<script src="{% static 'admin/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'admin/dist/js/adminlte.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<!--<script src="{% static 'admin/dist/js/demo.js' %}"></script>-->
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'admin/dist/js/pages/dashboard.js' %}"></script>


<script>
function confirmDelete() {
    return confirm('Are you sure you want to delete this student?');
}
</script>



</body>
</html>

admins/templates/admins/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Admin Login </title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static '/admin/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static '/admin/dist/css/adminlte.min.css' %}">
</head>
<body>
<div class="wrapper">
  <!-- Content Wrapper. Contains page content -->
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-6" style="margin-left:350px;">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header" style="text-align:center">
                <h3>Admin Login</h3>
              </div>





              <!-- /.card-header -->
              <!-- form start -->
              <form action="" method="POST">
                {% csrf_token %}
                <div class="card-body">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Email address</label>
                    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email" name="username">
                  </div>
                  <div class="form-group">
                    <label for="exampleInputPassword1">Password</label>
                    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" name="password">
                  </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary" name="submit">Submit</button>
                </div>
              </form>
            </div>
            <!-- /.card -->

          </div>
          <!--/.col (left) -->
          <!-- right column -->
            <!-- /.card -->
          </div>
          <!--/.col (right) -->
        </div>
        <!-- /.row -->
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  <!-- /.content-wrapper -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static 'admin/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'admin/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- bs-custom-file-input -->
<script src="{% static 'admin/plugins/bs-custom-file-input/bs-custom-file-input.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'admin/dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<!--<script src="{% static 'admin/dist/js/demo.js' %}"></script>-->
<!-- Page specific script -->
</body>
</html>

admins/templates/admins/student_edit.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Chisapani School Admin | Dashboard</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'admin/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bootstrap 4 -->
  <link rel="stylesheet" href="{% static 'admin/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'admin/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{% static 'admin/plugins/jqvmap/jqvmap.min.css'%}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'admin/dist/css/adminlte.min.css' %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'admin/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{% static 'admin/plugins/daterangepicker/daterangepicker.css' %}">
  <!-- summernote -->
  <link rel="stylesheet" href="{% static 'admin/plugins/summernote/summernote-bs4.min.css' %}">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->

            <li class="nav-item">
            <a href="#" class="nav-link active">
              <i class="fas fa-users"></i>
              <p>
                Students
                <i class="bi bi-people-fill"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'admins:studentadd' %}" class="nav-link active">
                  <i class="fas fa-user-plus"></i>
                  <p>Add Student</p>
                </a>
              </li>

               <li class="nav-item">
                <a href="{% url 'dashboard' %}" class="nav-link active">
                  <i class="fas fa-users"></i>
                  <p>List Student</p>
                </a>
              </li>

            </ul>
          </li>
        </ul>

      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <!-- Small boxes (Stat box) -->

        <!-- Main row -->
        <div class="row">
          <!-- Left col -->
          <section class="col-lg-12 connectedSortable">
<!--      student add form        -->

              <div class="col-md-10">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Student Edit Form</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form method="POST" action="">
               {% csrf_token %}
                <div class="card-body">
                    <div class="form-group">
                    <label for="exampleInputPassword1">Name</label>
                    <input type="text" class="form-control" id="exampleInputPassword1" value="{{student.name}}" name="name">
                  </div>
                  <div class="form-group">
                    <label for="exampleInputEmail1">Email address</label>
                    <input type="email" class="form-control" id="exampleInputEmail1" value="{{student.email}}" name="email">
                  </div>
                  <div class="form-group">
                    <label for="exampleInputPassword1">Address</label>
                    <input type="text" class="form-control" id="exampleInputPassword1" value="{{student.address}}" name="address">
                  </div>

                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
            <!-- /.card -->


          </div>






          </section>
          <!-- /.Left col -->

        </div>
        <!-- /.row (main row) -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <strong>Copyright &copy; 2081 OJT batch <a href="#">Chisapani Model Secondary School</a>.</strong>
    All rights reserved.
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static 'admin/plugins/jquery/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'admin/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{% static 'admin/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- ChartJS -->
<script src="{% static 'admin/plugins/chart.js/Chart.min.js' %}"></script>
<!-- Sparkline -->
<script src="{% static 'admin/plugins/sparklines/sparkline.js' %}"></script>
<!-- JQVMap -->
<script src="{% static 'admin/plugins/jqvmap/jquery.vmap.min.js' %}"></script>
<script src="{% static 'admin/plugins/jqvmap/maps/jquery.vmap.usa.js' %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static 'admin/plugins/jquery-knob/jquery.knob.min.js' %}"></script>
<!-- daterangepicker -->
<script src="{% static 'admin/plugins/moment/moment.min.js' %}"></script>
<script src="{% static 'admin/plugins/daterangepicker/daterangepicker.js' %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static 'admin/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<!-- Summernote -->
<script src="{% static 'admin/plugins/summernote/summernote-bs4.min.js' %}"></script>
<!-- overlayScrollbars -->
<script src="{% static 'admin/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'admin/dist/js/adminlte.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'admin/dist/js/pages/dashboard.js' %}"></script>
</body>
</html>